[package]
name = "amm-anchor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.23.0"
solana-program = "1.8.16"
spl-token = { version="3.2.0", features = [ "no-entrypoint" ] }
